### ISSUE TITLE
Stop using PEAR

### ISSUE THREAD

**Issue by atrauzzi** [Azure/azure-sdk-for-php#747] opened 2015-06-20 20:06 UTC
It's enough to say that PEAR is deprecated by composer.  But if that isn't enough for you, Fabien Potencier has a great post on the subject:

http://fabien.potencier.org/the-rise-of-composer-and-the-fall-of-pear.html

**Comment by jack71** [comment] 2015-06-29 11:56
:+1:

**Comment by roy128** [comment] 2015-08-03 20:40
:+1:

**Comment by lukasz-schab** [comment] 2015-08-11 12:59
Please remove PEAR from the project.

**Comment by gonimar** [comment] 2015-08-20 17:34
:+1:

**Comment by bzz445** [comment] 2015-08-20 17:34
:+1:

**Comment by arfr** [comment] 2015-08-21 20:43
:+1:

**Comment by bennsel** [comment] 2015-08-22 19:40
:+1:

**Comment by vohof** [comment] 2015-08-30 11:25
:+1:

**Comment by tibahut** [comment] 2015-09-07 07:50
:+1:

**Comment by josselinchevalay** [comment] 2015-09-07 07:51
+1

**Comment by Sparox** [comment] 2015-09-07 07:51
:+1:

**Comment by fbm-static** [comment] 2015-09-07 11:18
:+1: Unbelievable!

**Comment by gonimar** [comment] 2015-10-09 08:41
:+1:

**Comment by mediamonks-robert** [comment] 2015-10-12 10:02
+1

**Comment by forloops** [comment] 2015-10-16 14:15
:+1:

**Comment by jerodev** [comment] 2015-10-20 11:53
:+1:

**Comment by robholmes** [comment] 2015-10-29 14:39
+1

**Comment by euskadi31** [comment] 2015-11-02 15:25
:+1:

**Comment by DragonBe** [comment] 2015-11-12 14:30
Question to everyone who wants to remove the existing PEAR dependency: are you guys cool using [Guzzle](https://github.com/guzzle/guzzle) as HTTP client for all transactions with the Azure API?

It seems Guzzle is becoming the standard PHP HTTP client in applications and libraries and since it's adhering to the PSR's defined by the [PHP-FIG](http://www.php-fig.org) I think it's a good investment in the future. Also when we implement Guzzle, we don't have to reinvent the wheel so more attention can be spend on the implementation of the SDK.

I'd like to hear your opinion on this and if you have better suggestions I'd love to hear them.

**Comment by mediamonks-robert** [comment] 2015-11-14 07:38
Yes please, Guzzle is great :)

**Comment by DavidAnderson684** [comment] 2015-11-17 14:50
Yes, definitely Guzzle.

**Comment by adrianpietka** [comment] 2015-11-20 21:12
:+1:

**Comment by jeroenseegers** [comment] 2015-12-02 10:29
:+1: for Guzzle, in the meantime, I opened a PR which updates the `composer.json` to use the available PEAR packages from packagist.org

https://github.com/Azure/azure-sdk-for-php/pull/762

**Comment by atrauzzi** [comment] 2015-12-02 13:46
For anyone who does implement guzzle for this library, be sure to use the latest version as there is some ambiguity on packagist as to which one is the old one and which one is the current one.

**Comment by dominic-miglar** [comment] 2015-12-16 12:13
+1

**Comment by SInCE** [comment] 2015-12-16 12:15
:+1: for PEAR and Guzzle and everything. The PEAR-requirements can't be resolved by composer anymore as their package-name has been changed.

**Comment by euskadi31** [comment] 2015-12-16 12:46
Please not use Guzzle or other http client ! 
Use [PSR-7](http://www.php-fig.org/psr/psr-7/) and https://github.com/php-http/httplug

Slides: http://jolicode.github.io/httplug-conf/index.html#/ (Sorry the slides is in french).

**Comment by darxmac** [comment] 2015-12-16 14:56
So, loading PEAR via composer is just broken now ? what is the workaround, anyone know ?

**Comment by DragonBe** [comment] 2015-12-16 15:50
The new GuzzleHttp/Guzzle uses PSR7 😃

**Comment by euskadi31** [comment] 2015-12-16 15:56
See: http://docs.httplug.io/en/latest/

> HTTPlug allows you to write reusable libraries and applications that need an HTTP client **without binding to a specific implementation**. When all packages used in an application only specify HTTPlug, the application developers can chose the client that fits best for their project and use the same client with all packages.
>
> There are clients implementing one of the HTTPlug interfaces directly, and adapter packages that implement the interface and forward the calls to HTTP clients not implementing the interface.

**Comment by DragonBe** [comment] 2015-12-16 16:01
@darxmac 

I have the following setting in my composer.json
```javascript
...
  "repositories": [
    {
      "type": "pear",
      "url": "http://pear.php.net"
    }
  ],
  "require": {
    "php": ">=5.4",
    "pear-pear.php.net/mail_mime" : "^1.8",
    "pear-pear.php.net/http_request2" : "^2.2",
    "pear-pear.php.net/mail_mimedecode" : "^1.5",
    "microsoft/windowsazure": "^0.4"
    "predis/predis": "^1.0"
  },
  "require-dev": {
    "phpunit/phpunit": "^4.6"
  },
...
```

**Comment by DragonBe** [comment] 2015-12-16 16:03
Above example seems to be failing now :-1: 
```bash
Loading composer repositories with package information
Initializing PEAR repository http://pear.php.net
PEAR repository from http://pear.php.net could not be loaded. Undefined index: channel
```

**Comment by jeroenseegers** [comment] 2015-12-16 16:07
The PR I've opened (#762) proposes to use the PEAR packages which have been migrated to be used by packagist.org

**Comment by DragonBe** [comment] 2015-12-16 16:21
The temporarily solution I have at the moment is the following: use "http://us.pear.php.net"

```javascript
  "repositories": [
    {
      "type": "pear",
      "url": "http://us.pear.php.net/"
    }
  ],
  "require": {
    "php": ">=5.4",
    "pear-pear.php.net/mail_mime" : "^1.8",
    "pear-pear.php.net/http_request2" : "^2.2",
    "pear-pear.php.net/mail_mimedecode" : "^1.5",
    "microsoft/windowsazure": "^0.4"
  },
  "require-dev": {
    "phpunit/phpunit": "^4.6"
  },
...
```

This works currently both on my local machine as on Azure deploy

**Comment by DragonBe** [comment] 2015-12-16 16:21
but the solution from @jeroenseegers will solve the issue completely once the PR is accepted

**Comment by mandersondesign** [comment] 2015-12-16 16:40
Hey! We are having the same issue! We are going to try this solution... but the sooner we drop pear as a requirement for azure sdk... the better!

**Comment by hootener** [comment] 2015-12-16 16:49
+1 I pulled my hair out over this most of last night. http://pear2.php.net works fine, but doesn't contain the http_request2 package, so even that isn't a valid workaround. 

@DragonBe as hopeful as I was, the http://us.pear.php.net mirror seems to be down too: 

    Loading composer repositories with package information
    Initializing PEAR repository http://us.pear.php.net
    PEAR repository from http://us.pear.php.net could not be loaded. 
    The "http://us.pear.php.net/channel.xml" file could not be downloaded: failed to open stream: Connection timed out
    Updating dependencies (including require-dev)


and the http://de.pear.php.net suffers from the same issue of ```PEAR repository from http://de.pear.php.net could not be loaded. Undefined index: channel```

This is incredibly frustrating and can't wait to see PEAR dropped as a requirement from the Azure-PHP-SDK.

**Comment by mandersondesign** [comment] 2015-12-16 17:15
Temporary Solution:

We forked the repo, and incorporated @jeroenseegers changes to composer.json

In order to use it, go ahead and remove the pear reference from the repository section, and replace it with the following:

```
    {
      "type" : "vcs",
      "url": "https://github.com/GameWisp/azure-sdk-for-php.git"
    }
```

in the require section, set microsoft/windowsazure to dev-master:

```
"require": {
    ...
    "microsoft/windowsazure": "dev-master",
    ...
}
```

finally, make sure your minimum-stability in the root section of the file is set to dev:

```
"minimum-stability": "dev"
```

**Comment by DragonBe** [comment] 2015-12-16 17:18
I've collected thus far only a few requirements for storage, need to get started on that and have something out ASAP. Further services can be added as we go.

**Comment by Maras0830** [comment] 2015-12-17 05:43
@mandersondesign  thanks,  i use your method and solved it :)

**Comment by devigned** [comment] 2016-03-12 15:37
@yaqiyang & @YuvalMazor  we need to get this addressed as soon a possible.

**Comment by phansys** [comment] 2016-03-20 22:23
@devigned, @yaqiyang, @YuzorMa; I can take a look at this if you first provide an open test suite for the package. Since I'm not a direct user of this library, I need a platform where the expected behavior can be checked within the current dependency (`pear/http_request2` & co.).

**Comment by yaqiyang** [comment] 2016-03-22 00:27
@phansys , thanks for your contribution to our project. There are two issues. The original proposal here is clearly to remove PEAR as a package manager which we are planning to do pretty soon. The second is to remove PEAR packages as dependencies which we are still evaluating. I am also working on the tests for the project, so I cannot provide you with a test suite just yet. If you have ideas on what packages should be replacing PEAR, please share with us. 

Thanks
Yaqi

**Comment by phansys** [comment] 2016-03-24 21:38
@yaqiyang, sorry for the delay.
First of all, the cleanest replacement have place between `pear/http_request2` and [`guzzlehttp/guzzle`](http://docs.guzzlephp.org/en/latest/) (which is also [PSR-7](http://www.php-fig.org/psr/psr-7/) compliant).
About the others, I haven't formed a strong decision yet since I never used any of those dependencies, that's why I'm requiring a test suite.
BTW, I encourage you to browse available replacements on [Packagist](https://packagist.org/) too.

Regards.

**Comment by yaqiyang** [comment] 2016-04-04 15:59
I have removed PEAR as package manager by https://github.com/Azure/azure-sdk-for-php/pull/792. Opened a new issue https://github.com/Azure/azure-sdk-for-php/issues/797 to find replacements for PEAR packages. 

Thanks 
Yaqi

**Closed by yaqiyang** 2016-04-04 15:59 UTC

**Comment by fbm-static** [comment] 2016-05-09 10:08
All these +1s and nobody bothered to said thanks when it has been done.

**Comment by mandersondesign** [comment] 2016-05-12 20:44
Ha. Didn't even see it. Thanks!

**Comment by DragonBe** [comment] 2016-05-12 21:13
Sorry folks that I was silent for a couple of months, but I already started a rebuild. Progress is slow because of many other things that I have to do, but I'm motivated to continue working on this.

Find the repo at https://github.com/DragonBe/azure-sdk-for-php7 (requires PHP 7). Some things I need to further investigate: the best way to implement PSR-7 middleware, introducing a solid DI platform and more best practices.


I use PHPUnit for testing and hooked the repo up onto [ContinuousPHP](https://www.continuousphp.com) for continuous integration.

Please have a look at it and give me your honest opinion (please be gentle). I'm sorry I cannot proceed any faster.
