### ISSUE TITLE
Tracking Encoding Percentage Status

### ISSUE THREAD

**Issue by adityosnrost** [Azure/azure-sdk-for-php#846] opened 2016-06-14 05:23 UTC
Hi,

I would like to know how to tracking my encoding job within percentage status. I have only found the function to know if the job has finished or not. Is there any function that return percentage of task or job ?

Thanks

Best Regards,

Adityo Setyonugroho

**Comment by yaqiyang** [comment] 2016-06-14 15:36
The way to track progress is to get the Tasks and Task has a Progress property. 

```
        $mytasks = $restProxy->getJobTasks($job);
        $progress = $mytasks[0]->getProgress();
```
$progress will range from 0 to 100. But the problem is this functionality does not seem to have been implemented since it returns 0 and then 100 at the finish of the task. No middle points were returned in my testing. The documentation for this REST call is at https://msdn.microsoft.com/en-us/library/azure/hh974286.aspx. Please test it for yourself and see if it ever returns middle points.

**Comment by adityosnrost** [comment] 2016-06-14 22:33
Hi, thanks for your reply. I'll be working around with that, I'll update the result here. Thanks

**Comment by yaqiyang** [comment] 2016-06-20 16:03
@adityosnrost , any update? Can I close this issue?

Thanks
Yaqi

**Comment by scorpioliu3** [comment] 2016-06-21 14:01
how about this problem, what is wrong with my steps ?

C:\azure-sdk-for-php-master\examples\MediaServices>php -d display_errors=1 scale
_encoding_units.php
Azure SDK for PHP - Scale Encoding Units Sample

Fatal error: Uncaught WindowsAzure\Common\ServiceException: Fail:
Code: 400
Value: Bad Request
details (if any): {"error":"invalid_client","error_description":"ACS50012: Authe
ntication failed.\r\nTrace ID: 9b51070c-678e-4d4d-95ec-c1dc2918de4c\r\nCorrelati
on ID: f835e420-6fc1-408e-926d-b132f3c1961a\r\nTimestamp: 2016-06-21 13:36:46Z"}
. in C:\azure-sdk-for-php-master\examples\vendor\microsoft\windowsazure\WindowsA
zure\Common\Internal\Http\HttpClient.php:384
Stack trace:
#0 C:\azure-sdk-for-php-master\examples\vendor\microsoft\windowsazure\WindowsAzu
re\Common\Internal\Http\HttpClient.php(277): WindowsAzure\Common\Internal\Http\H
ttpClient::throwIfError(400, 'Bad Request', '{"error":"inval...', Array)
#1 C:\azure-sdk-for-php-master\examples\vendor\microsoft\windowsazure\WindowsAzu
re\Common\Internal\RestProxy.php(143): WindowsAzure\Common\Internal\Http\HttpCli
ent->send(Array, Object(WindowsAzure\Common\Internal\Http\Url))
#2 C:\azure-sdk-for-php-master\examples\vendor\microsoft\windowsazure\WindowsAzu
re\Common\Internal\ServiceR in C:\azure-sdk-for-php-master\examples\vendor\micro
soft\windowsazure\WindowsAzure\Common\Internal\Http\HttpClient.php on line 384

**Comment by boredom2** [comment] 2016-06-21 14:18
The answer is correct and I can confirm, that getPercent() indeed returns values between 0 and 100 - working really fast and good :)

**Comment by yaqiyang** [comment] 2016-06-21 14:55
It seems you don’t have the correct authentication credentials ($account and $secret). Please open an new issue if you still have this problem. I am closing the old issue.

Thanks
Yaqi

**Closed by yaqiyang** 2016-06-21 14:55 UTC
